on:
  schedule:
   - cron: "5 * * * *"
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Run bash script
#        run: bash spamhaus.sh
#on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ${GITHUB_WORKSPACE}/spamhaus.sh
         ${GITHUB_WORKSPACE}/spamhaus.sh
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v4
      #with:
      #  commit_message: Changed files      
