on:
  schedule:
    - cron: "5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run bash script
        run: bash spamhaus.sh
